gpu: -1
multi_gpu: false
gpu_ids: [0, 1, 2]
num_workers: 10  # number of CPU cores for parallel tasks
pretrained_model_root: /data/UKBB/gert/ssl/logging/cv_output/0

# location where to save prediction outputs
ukb_output_path: outputs

# For offline usage only (eg BMRC): set this to the location of the OxWearables/ssl-wearables repository.
# Leave empty otherwise (will auto download repo from Github when empty).
ssl_repo_path:

sslnet:
  weights: weights/state_dict.pt
  augmentation: true
  weighted_loss_fn: true
  learning_rate: 0.0001
  patience: 10
  num_epoch: 100

hmm:
  weights_ssl: weights/hmm_ssl.npz
  weights_rf: weights/hmm_rf.npz
  uniform_prior: true

rf:
  path: weights/rf.joblib

data:
  name: 'capture24'
  output_size: 4
  data_root: /data/UKBB/capture24_30hz_w30_o0
  X_path: "${.data_root}/X.npy"
  Y_path: "${.data_root}/Y_Walmsley.npy"
  PID_path: "${.data_root}/pid.npy"
  time_path: "${.data_root}/time.npy"
  sample_rate: 30
  input_size: 900


