gpu: -1
multi_gpu: false
gpu_ids: [0, 1, 2]
num_workers: 10  # number of CPU cores for parallel tasks
num_folds: 5 # number of folds in the cross validation

# location where to save prediction outputs
ukb_output_path: outputs

# For offline usage only (eg BMRC): set this to the location of the OxWearables/ssl-wearables repository.
# Leave empty otherwise (will auto download repo from Github when empty).
ssl_repo_path:

sslnet:
  enabled: true
  weights: weights/state_dict_{}.pt
  overwrite: false
  augmentation: true
  weighted_loss_fn: true
  learning_rate: 0.0001
  patience: 10
  num_epoch: 100
  batch_size: 100

rf:
  enabled: true
  path: weights/rf_{}.joblib

hmm:
  weights_ssl: weights/hmm_ssl_{}.npz
  weights_rf: weights/hmm_rf_{}.npz
  uniform_prior: true

hmm_learn:
  weights_ssl: weights/hmm_learn_ssl_{}.npz
  weights_rf: weights/hmm_rf_{}.npz
  uniform_prior: true

data:
  name: OxWalk
  data_root: /data
  raw_data: "${.data_root}/raw"
  processed_data: "${.data_root}/processed"
  X_path: "${.processed_data}/X.npy"
  Y_path: "${.processed_data}/Y_is_walk.npy"
  PID_path: "${.processed_data}/Y_pid.npy"
  time_path: "${.processed_data}/T.npy"
  sample_rate: 30
  winsec: 10
  step_threshold: 4
  
