gpu: -1
multi_gpu: false
gpu_ids: [0, 1, 2]
num_workers: 10  # number of CPU cores for parallel tasks

# location where to save prediction outputs
output_path: outputs

# For offline usage only (eg BMRC): set this to the location of the OxWearables/ssl-wearables repository.
# Leave empty otherwise (will auto download repo from Github when empty).
ssl_repo_path:

training:
  cv_type: LeaveOneGroupOut
  num_folds: 5
  val_split: 0.2
  external_val:

sslnet:
  enabled: true
  overwrite: false
  weights: weights/ssl/state_dict_{}.pt
  augmentation: true
  weighted_loss_fn: true
  learning_rate: 0.0001
  patience: 10
  num_epoch: 100
  batch_size: 100

rf:
  enabled: true
  overwrite: false
  path: weights/rf/model_{}.joblib

hmm:
  weights_ssl: weights/ssl/hmm_{}.npz
  weights_rf: weights/rf/hmm_{}.npz
  uniform_prior: true

hmm_learn:
  weights_ssl: weights/ssl/hmm_learn_{}.npz
  weights_rf: weights/rf/hmm_learn_{}.npz
  uniform_prior: true

peak_counter:
  enabled: true
  overwrite: true
  weights_ssl: weights/ssl/{}_peak_counter_{}.npy
  weights_rf: weights/rf/{}_peak_counter_{}.npy

data:
  sources: ["OxWalk"]
  overwrite: false
  data_root: C:/Users/AidenA/Documents/Projects/ssl-walking/data
  raw_data: "${.data_root}/raw"
  processed_data: "${.data_root}/processed"
  X_path: "${.processed_data}/X.npy"
  Y_path: "${.processed_data}/Y_is_walk.npy"
  PID_path: "${.processed_data}/Y_pid.npy"
  time_path: "${.processed_data}/T.npy"
  source_path: "${.processed_data}/Y_source.npy"
  steps_path: "${.processed_data}/Y_steps.npy"
  sample_rate: 30
  winsec: 10
  step_threshold: 4
